title: Afera NetiaGate
description: >-
  Dekodery Netii nie przechodzą w stan uśpienia (standby) mimo zapalonej 
  czerwonej diody i powoływania się na rozporządzenia w deklaracji zgodności
lang: pl-PL
